import '@styles/globals.css'
import { Inter } from 'next/font/google'

import Footer from '@components/Footer'
import Nav from '@components/Nav'
import SideMenuWrapper from '@components/SideMenuWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NBP Fork',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Nav/>
          <main>
            <SideMenuWrapper>
              {children}
            </SideMenuWrapper>
          </main>
        </div>
      </body>
    </html>
  )
}
