/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.letusplay.mongodb;

import com.mongodb.client.ListDatabasesIterable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import org.bson.Document;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    String MONGO_URL = "mongodb://root:123456@localhost:27017/payment?authSource=admin";

    System.out.println(new App().getGreeting());
    try ( MongoClient mongoClient = MongoClients.create(MONGO_URL) ) {
      MongoClien
      MongoCollection<Document> collection = database.getCollection("movies");
      ListDatabasesIterable<Document> dbs = mongoClient.listDatabases();
      dbs.forEach(System.out::println);
    }
  }
}
